[package]
name = "gen_notes"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
# Workspace
anyhow.workspace = true
camino.workspace = true
clap.workspace = true

[lints]
workspace = true
