# Use this for testing production
# base = "https://bencher.dev"
timeout = 5
max_retries = 3
retry_wait_time = 1
exclude = [
    "localhost:3000",
    "http://localhost:3000*",
    "http://localhost:61016*",
    "http://127.0.0.1:61016*",
    "http://host.docker.internal:61016*",
    "https://api.bencher.dev*",
    "https://api.bencher.example.com*",
    "https://discord.gg/yGEsdUh7R4",
    "https://github.com/bencherdev/bencher/issues/new*",
    "https://www.linkedin.com/in/epompeii/",
    "https://www.linkedin.com/company/bencher",
    "https://www.reddit.com/r/bencher",
    "https://gitlab.com/api/*",
    "https://0123abc1023abc@987efg987efg.ingest.sentry.io/0123456789",
    "https://www.nsa.gov/Cybersecurity/Partnership/National-Cross-Domain-Strategy-Management-Office/",
    "saul@bettercallsaul.com",
    # TODO figure out why this page 404s
    # "https://bencher.dev/docs/[a-z]{2}/reference/api",
]
# TODO remove exclude paths once `--cookie-jar` is stable
# https://github.com/lycheeverse/lychee/commit/14e748793e8a08d7c2130f63896074f4980204cb
# Netlify paths
exclude_path = [
    "./services/console/dist/docs/reference/prior-art/index.html",
    "./services/console/dist/de/docs/reference/prior-art/index.html",
    "./services/console/dist/es/docs/reference/prior-art/index.html",
    "./services/console/dist/fr/docs/reference/prior-art/index.html",
    "./services/console/dist/ja/docs/reference/prior-art/index.html",
    "./services/console/dist/ko/docs/reference/prior-art/index.html",
    "./services/console/dist/pt/docs/reference/prior-art/index.html",
    "./services/console/dist/ru/docs/reference/prior-art/index.html",
    "./services/console/dist/zh/docs/reference/prior-art/index.html",
]
